config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  root  'users#home'
  match '/show', to: 'users#show', via: 'get'
  match '/signup', to: 'users#new', via: 'get'
  match '/rules', to: 'users#rules', via: 'get'
  match '/edit', to: 'users#edit', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout',to: 'sessions#destroy', via: 'delete'

end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  before_create :create_remember_token
  validates :name, length: { maximum: 20 }, presence: true, format: { with: /\A[a-zA-Z]+\z/, message: 'only allows letters' }
  validates :surname, presence: true
  validates :age, numericality: { greater_than: 0, less_than: 100 }
  validates :email, uniqueness: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  has_secure_password
  validates :password, length: { minimum: 6 }
  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

  def create_remember_token
    self.remember_token = User.encrypt(User.new_remember_token)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      render 'show'
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:edit, :update]

  def home
  end
  def new
  	@user = User.new
  end
  def edit
    @user = User.find(params[:id])
  end
  def show
    @user = User.find(params[:id])
  end
  def create
  	@user = User.new(user_params)
  	if @user.save
      sign_in @user
  		redirect_to @user
  	else
  		render '_error_messages'
  	end
  end
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = 'Profile updated'
      redirect_to @user
    else
      render 'edit'
    end
  end
  private
  def user_params
  	params.require(:user).permit(:name, :surname, :age, :email, :password, :password_confirmation, :sex, :phone, :status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user?(user)
    user == current_user
  end

  def sign_out
    current_user.update_attribute(:remember_token,
                                  User.encrypt(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end
    def signed_in_user
    unless signed_in?
      redirect_to signin_url, notice: 'Please sign in.'
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header class='navbar'>
  <div >
    <span id='logo'>The Game</span>
    <nav class='nav pull-right'>
      <span><%= link_to 'Home', root_path %></span>
        <% if signed_in? %>
          <span class='dropdown'>
            <a href='#' class='dropdown-toggle' data-toggle='dropdown'>
              Account <b class='caret'></b>
            </a>
            <ul class='dropdown-menu'>
              <li><%= link_to 'Rules', rules_path %></li>
              <li><%= link_to 'Edit Your Profile', edit_user_path(current_user) %></li>
              <li class='divider'></li>
              <li>
                <%= link_to 'Sign out', signout_path, method: 'delete' %>
              </li>
            </ul>
          </span>
        <% else %>
          <span><%= link_to 'Sign in', signin_path %></span>
        <% end %>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The Game</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
</head>
<body>
	<%= render 'layouts/header' %>
	<%= yield %>
</body>
</html>

app/views/users/_error_messages.html.erb
<div id='fail'>
  <div class='container'>
    <h2>Registration failed</h2>
    <h3>Smthng wrng...</h3>
    <% if @user.errors.any? %>
      <div id='error_explanation'>
        <div class='alert alert-error'>
          The form contains <%= pluralize(@user.errors.count, 'error') %>.
        </div>
        <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li>* <%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <h3>Try again=)</h3>
    <h4>||</br>||</br>||</br>V</br></h4>
    <a href='/signup'><h3>Sign up again</h3></a>
  </div>
</div>

app/views/users/edit.html.erb
<div id='edit'>
  <h1 id='whiteText'>Update your profile</h1>
  <div class='row'>
    <div class='span6 offset3'>
      <%= form_for(@user) do |f| %>
        <%= f.label :name %>
        <%= f.text_field :name %></br>

        <%= f.label :surname, "Surname: #{@user.errors[:surname].join('')}" %>
        <%= f.text_field :surname %></br>

        <%= f.label :age, 'Age:' %>
        <%= f.number_field :age, in: 1.0..100.0, step: 1.0 %></br>

        <%= f.label :email %>
        <%= f.text_field :email %></br>

        <%= f.label :password %>
        <%= f.password_field :password %></br>

        <%= f.label :password_confirmation, 'Confirm Password' %>
        <%= f.password_field :password_confirmation %></br>

        <%= f.label :sex, 'Sex:' %>
        <%= f.radio_button(:sex, 'male') %>
        <%= f.label(:sex_male, 'Male') %>
        <%= f.radio_button(:sex, 'female') %>
        <%= f.label(:sex_female, 'Female') %></br>

        <%= f.label :phone, 'Phone number:' %>
        <%= f.text_field :phone %></br>

        <%= f.label :status, 'Status:' %>
        <%= f.select :status, [["I'm sexy and I know it",'sexy'],['Married','married'],['Single','single'],['Have a friend','friend']] %><br>
  </br>
        <%= f.submit 'Save changes', class: 'btn' %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/home.html.erb
<div id='home'>
<h1 id='greyText'>Do you wanna play a little game?</h1>
	<div>
    <button class='button1' onclick="window.location.href='/signup'"><p id='button1'>Play Game</p></button>
  </div>
</div>

app/views/users/new.html.erb
<div class='container' id='reg'>
  <div class='row'>
    <div class='col-sm-5 col-sm-offset-1'>
      <h1 id='whiteText'>New User Registration</h1>
      <%= form_for(@user) do |f|%>
        <%= f.label :name, "Name: #{@user.errors[:name].join('')}" %>
        <%= f.text_field :name %><br>
        <%= f.label :surname, "Surname: #{@user.errors[:surname].join('')}" %>
        <%= f.text_field :surname %><br>
        <%= f.label :age, 'Age:' %>
        <%= f.number_field :age, in: 1.0..100.0, step: 1.0 %><br>
        <%= f.label :email, 'Email:' %>
        <%= f.email_field :email %><br>
        <%= f.label :password, 'Password:' %>
        <%= f.password_field :password %><br>
        <%= f.label :password_confirmation, 'Password Confirmation:' %>
        <%= f.password_field :password_confirmation %><br>
        <%= f.label :sex, 'Sex:' %>
        <%= f.radio_button(:sex, 'male') %>
        <%= f.label(:sex_male, 'Male') %>
        <%= f.radio_button(:sex, 'female') %>
        <%= f.label(:sex_female, 'Female') %><br>
        <%= f.label :phone, 'Phone number:' %>
        <%= f.text_field :phone %><br>
        <%= f.label :status, 'Status:' %>
        <%= f.select :status, [["I'm sexy and I know it",'sexy'],['Married','married'],['Single','single'],["Have a friend",'friend']] %><br>
        </br>
      <%= f.submit 'Create my account', class:'btn' %>
      <% end %>
      </div>
    <div class='col-sm-4'>
    <h1 id='whiteText'>Sign in</h1>
      <%= form_for(:session, url: sessions_path) do |f| %>
        <%= f.label :email %>
        <%= f.text_field :email %><br>
        <%= f.label :password %>
        <%= f.password_field :password %><br>
        </br>
        <%= f.submit 'Sign in', class:'btn'%><br>
      <% end %>
    </div>
    <div class='col-sm-2'>
    </div>
  </div>
</div>

app/views/users/rules.html.erb
<div id='rule'>
  <div class="container" id='whiteText'>
    <h2 id='ruleText'>Rules</h2>
    <h3><img src="http://6.firepic.org/6/images/2015-12/14/k7614elqbu23.gif" alt="saw" align="left" vspace="5" hspace="5">
    Rock-paper-scissors is a zero sum hand game usually played
    between two people, in which each player simultaneously forms
    one of three shapes with an outstretched hand. These shapes
    are "rock" (a simple fist), "paper" (a flat hand), and
    "scissors" (a fist with the index and middle fingers together
    	forming a V). The game has only three possible outcomes
    other than a tie: a player who decides to play rock will beat
    another player who has chosen scissors ("rock crushes
    	scissors") but will lose to one who has played paper
    ("paper covers rock"); a play of paper will lose to a play of
    scissors ("scissors cut paper"). If both players throw the
    same shape, the game is tied and is usually immediately
    replayed to break the tie. Other names for the game in the
    English-speaking world include roshambo and other orderings
    of the three items, sometimes with "rock" being called
    "stone".
    </h3>
  </div>
</div>

app/views/users/show.html.erb
<div class='container' id='user'>
	<h1 id='whiteText'>Congratulations! <%= @user.name %> <%= @user.surname %></h1>
	<h3 id='whiteText'>If you want to play a game, please <%= link_to 'Sign in', signin_path, method: 'get' %>
  </br>
  </br>
	<%= link_to 'Sign out', signout_path, method: 'delete' %></h3>
</div>